Agency_Backoffice/Agency_Backoffice/Controllers/WalletController.cs
using Agency_Backoffice.Models;
using Agency_Backoffice.Models.Common;
using Agency_Backoffice.Service;
using ModelLibrary;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Agency_Backoffice.Controllers
{
    public class WalletController : Controller
    {
        #region [Upload Request]
        public ActionResult UploadRequest(UploadRequest model)
        {
            AgencyLoginSession lu = new AgencyLoginSession();
            try
            {
                if (AccountService.IsAgencyLogin(ref lu))
                {
                    string distr = lu.Distr;
                    if (distr.ToUpper().Trim() == "FWU")
                    {
                        model.IsShowReqType = true;
                    }

                    model.DepositeBankList = Commoncls.PopulateDepositeBank(WalletService.DepositeBankList(lu.User_Id));
                    model.DepositeOfficeList = Commoncls.PopulateDepositeOffice(WalletService.DepositeOfficeList(lu.User_Id));
                    model.DepositeBranchList = Commoncls.PopulateAccountAndBranch(WalletService.DepositeAccountAndBranch(null, null));
                    model.DepositeAccountNoList = Commoncls.PopulateAccountAndBranch(WalletService.DepositeAccountAndBranch(null, null));
                    if (!string.IsNullOrEmpty(model.Amount) && !string.IsNullOrEmpty(model.PaymentMode))
                    {
                        model.AgencyName = lu.Agency_Name;
                        model.AgencyID = lu.User_Id;
                        model.UploadeRequestType = "CA";
                        model.AgentType = lu.Agent_Type;
                        model.Status = "Pending";
                        //if (WalletService.InsertDepositDetail(model))
                        //{
                            TempData["Msg"] = "Upload Request Sent Sucessfully ...";
                        //}
                    }
                    ModelState.Clear();
                    model.PaymentMode = "";
                    model.Amount = "";
                    model.Remark = "";
                    model.ReferenceNumber = "";
                    model.ReceiptNumber = "";

                    //Search record
                    //UploadModelFilter filter = new UploadModelFilter();
                    //LoginSessionDetails lu2 = new LoginSessionDetails();
                    //if (AccountService.GetLoginSession(ref lu2))
                    //{
                    //    filter.UserType = lu2.AgentRegisterSession.User_Type;
                    //    filter.Loginid = lu2.AgentRegisterSession.UID;
                    //    filter.SearchType = "Own";
                    //}
                    //filter.FromDate = model.FilterFromDate;
                    //filter.ToDate = model.FilterToDate;
                    //filter.PaymentType = model.FilterPaymentType;
                    //filter.Status = model.FilterStatus;

                    //model.UploadDetialsList = WalletService.GetUploadDetials(filter);
                    //model.Totalcount = model.UploadDetialsList.Count;
                }
                else
                {
                    if (AccountService.LogoutBackendLogin())
                    {
                        Response.Redirect(Config.WebsiteLoginUrl);
                    }
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }
        public ActionResult ReportUploadRequest(UploadRequest model)
        {
            AgencyLoginSession lu = new AgencyLoginSession();
            try
            {
                if (AccountService.IsAgencyLogin(ref lu))
                {
                    string distr = lu.Distr;
                    if (distr.ToUpper().Trim() == "FWU")
                    {
                        model.IsShowReqType = true;
                    }

                    model.DepositeBankList = Commoncls.PopulateDepositeBank(WalletService.DepositeBankList(lu.User_Id));
                    model.DepositeOfficeList = Commoncls.PopulateDepositeOffice(WalletService.DepositeOfficeList(lu.User_Id));
                    model.DepositeBranchList = Commoncls.PopulateAccountAndBranch(WalletService.DepositeAccountAndBranch(null, null));
                    model.DepositeAccountNoList = Commoncls.PopulateAccountAndBranch(WalletService.DepositeAccountAndBranch(null, null));
                    if (!string.IsNullOrEmpty(model.Amount) && !string.IsNullOrEmpty(model.PaymentMode))
                    {
                        model.AgencyName = lu.Agency_Name;
                        model.AgencyID = lu.User_Id;
                        model.UploadeRequestType = "CA";
                        model.AgentType = lu.Agent_Type;
                        model.Status = "Pending";
                        if (WalletService.InsertDepositDetail(model))
                        {
                            TempData["Msg"] = "Upload Request Sent Sucessfully ...";
                        }
                    }
                    ModelState.Clear();
                    model.PaymentMode = "";
                    model.Amount = "";
                    model.Remark = "";
                    model.ReferenceNumber = "";
                    model.ReceiptNumber = "";

                    //Search record
                    UploadModelFilter filter = new UploadModelFilter();
                    LoginSessionDetails lu2 = new LoginSessionDetails();
                    if (AccountService.GetLoginSession(ref lu2))
                    {
                        filter.UserType = lu2.AgentRegisterSession.User_Type;
                        filter.Loginid = lu2.AgentRegisterSession.UID;
                        filter.SearchType = "Own";
                    }
                    filter.FromDate = model.FilterFromDate;
                    filter.ToDate = model.FilterToDate;
                    filter.PaymentType = model.FilterPaymentType;
                    filter.Status = model.FilterStatus;

                    model.UploadDetialsList = WalletService.GetUploadDetials(filter);
                    model.Totalcount = model.UploadDetialsList.Count;
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }
        public JsonResult BindDepositeBranch(string bank)
        {
            List<string> branchList = new List<string>();

            AgencyLoginSession lu = new AgencyLoginSession();
            if (AccountService.IsAgencyLogin(ref lu))
            {
                branchList = WalletService.DepositeAccountAndBranch("branch", bank, "Branch" + lu.User_Id);
            }

            return Json(branchList);
        }
        public JsonResult BindDepositeAccountNo(string bank)
        {
            List<string> accountList = new List<string>();

            AgencyLoginSession lu = new AgencyLoginSession();
            if (AccountService.IsAgencyLogin(ref lu))
            {
                accountList = WalletService.DepositeAccountAndBranch("office", bank, "Acc" + lu.User_Id);
            }

            return Json(accountList);
        }
        #endregion
        public ActionResult UploadRequestStatus(UploadModelFilter filter)
        {
            UploadModel model = new UploadModel();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    filter.UserType = lu.AgentRegisterSession.User_Type;
                    filter.Loginid = lu.AgentRegisterSession.UID;
                    filter.SearchType = "Own";
                }

                model.UploadDetialsList = WalletService.GetUploadDetials(filter);
                model.Totalcount = model.UploadDetialsList.Count;
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public ActionResult Bankdetails()
        {
            return View();
        }
        public ActionResult CashInFlow(UploadModelFilter filter)
        {
            UploadModel model = new UploadModel();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    filter.UserType = lu.AgentRegisterSession.User_Type;
                    filter.Loginid = lu.AgentRegisterSession.UID;
                    filter.SearchType = "Own";
                }

                model.UploadDetialsList = WalletService.GetCashInflowDetails(filter);
                model.Totalcount = model.UploadDetialsList.Count;
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public ActionResult AddEditbankList(BankModel model)
        {
            LoginSessionDetails lu = new LoginSessionDetails();
            try
            {
                if (AccountService.GetLoginSession(ref lu))
                {
                    model.Agentid = lu.AgentRegisterSession.UID;
                    if (!string.IsNullOrEmpty(model.BankName) && !string.IsNullOrEmpty(model.BranchName) && !string.IsNullOrEmpty(model.AccountNumber) && !string.IsNullOrEmpty(model.NEFTCode))
                    {
                        model.Operation = "INSERT";
                        if (WalletService.InsertBankdetials(model))
                        {
                            TempData["Msg"] = "bank Added Successfully ...";
                        }
                    }
                    model.Banklist = WalletService.GetDistributorBankDetails(model);
                    model.Totalcount = model.Banklist.Count;
                    ModelState.Clear();

Agency_Backoffice/Agency_Backoffice/Views/Wallet/AddEditbankList.cshtml
@model ModelLibrary.BankModel
@{
    ViewBag.Title = "AddEditbankList";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/fancybox/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/Content/css/Checkbox.css.css" rel="stylesheet" />
    <link href="~/Content/css/validation.css" rel="stylesheet" />
    <script src="~/Content/js/common.js"></script>
    
}
<div class="col-md-12">
    <div class="x_panel">
        @*<div class="x_title">
            <div class="row">
                <div class="col-sm-12">
                    <h4><i class="fa fa-bank"></i>&nbsp;Add Bank Details</h4>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>*@
        <div class="x_content">

            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <div class="row">
                                <div class="col-md-12">
                                    @if (TempData["Msg"] != null)
                                    {
                                        <div class="alert alert-success" id="closeMessage">

                                            <span>@TempData["Msg"]</span>
                                        </div>
                                    }

                                </div>
                            </div>
                            <header class="panel-heading">
                                Add Bank Details

                            </header>
                            <div class="panel-body" style="padding:15px;">
                                @using (Html.BeginForm())
                                {
                                    <div class="row form-group">
                                        <div class="col-sm-12 form-group">
                                            <div class="col-sm-2 form-validation">

                                                @Html.TextBoxFor(p => p.BankName, new { @class = "form-control", placeholder = "Enter bank name.." })
                                            </div>
                                            <div class="col-sm-2 form-validation">

                                                @Html.TextBoxFor(p => p.BranchName, new { @class = "form-control", placeholder = "Enter branch name.." })
                                            </div>
                                            <div class="col-sm-2 form-validation">

                                                @Html.TextBoxFor(p => p.Area, new { @class = "form-control", placeholder = "Enter area.." })
                                            </div>
                                            <div class="col-sm-2 form-validation">

                                                @Html.TextBoxFor(p => p.AccountNumber, new { @class = "form-control", placeholder = "Enter account number.." })
                                            </div>
                                            <div class="col-sm-2 form-validation">

                                                @Html.TextBoxFor(p => p.NEFTCode, new { @class = "form-control", placeholder = "Enter ifsc code.." })
                                            </div>
                                            <div class="col-sm-2">
                                                <input type="submit" class="btn btn-success form-control maincss" style="cursor:pointer;margin-top:1px" onclick="return CheckForm()" value="SUBMIT" />
                                                <span class="btn btn-success form-control tempscss hidden" style="margin-top:25px">PLEASE WAIT..<i class="fa fa-spinner fa-spin"></i></span>
                                            </div>
                                        </div>

                                    </div>
                                }
                            </div>
                        </section>
                    </div>
                </div>
            </section>



            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Bank Details

                            </header>
                            <div class="panel-body table-responsive" style="overflow:scroll;">
                                <table class="table table-bordered table-hover" data-toggle="table">
                                    <thead>
                                        <tr>
                                            <th>Bank Name</th>
                                            <th>Branch Name</th>
                                            <th>Area</th>
                                            <th>Account Number</th>
                                            <th>NEFT Code</th>
                                            <th>Created Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.Totalcount > 0)
                                        {
                                            foreach (var item in Model.Banklist)
                                            {
                                                <tr>
                                                    <td>@item.BankName</td>
                                                    <td>@item.BranchName</td>
                                                    <td>@item.Area</td>
                                                    <td>@item.AccountNumber</td>
                                                    <td>@item.NEFTCode</td>
                                                    <td>@item.CreatedDate</td>
                                                    <td>
                                                        <a data-fancybox-type="iframe" data-toggle="tooltip" title="Update" data-fancybox-href="/upload/edit-bank?counter=@item.Counter&bankname=@item.BankName&branchname=@item.BranchName&area=@item.Area&neftcode=@item.NEFTCode&accno=@item.AccountNumber" class="btn btn-success btn-sm popupclassreload anchorlinkred"><span class="fa fa-edit" style="color:#fff!important"></span></a>
                                                        <a href="/upload/delete-bank?counter=@item.Counter" data-toggle="tooltip" title="Delete" onclick="javascript: return DeleteConfirm();" class="btn btn-danger btn-sm"><span class="fa fa-remove"></span></a>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                            </section>
                        </div>
                    </div>
                </section>
                    </div>
                </div>
        </div>

@section footer{
    <script src="~/Content/fancybox/jquery.fancybox.js"></script>
    <script src="~/Content/fancybox/fancyboxpopupopen.js"></script>

    <script>
        function DeleteConfirm() {
            return confirm('Are you sure, you want to delete the bank ?');
        }
        function CheckForm() {
            if (CheckBlankValidation('BankName')) return !1;
            if (CheckBlankValidation('BranchName')) return !1;            
            if (CheckBlankValidation('Area')) return !1;
            if (CheckBlankValidation('AccountNumber')) return !1;
            if (CheckBlankValidation('NEFTCode')) return !1;
            $('.maincss').addClass('hidden');
            $('.tempscss').removeClass('hidden');
        }
    </script>
}

Agency_Backoffice/Agency_Backoffice/Views/Wallet/EditBank.cshtml
@model ModelLibrary.BankModel
@{
    ViewBag.Title = "EditBank";
    Layout = "~/Views/Shared/_PopupLayoutPage.cshtml";
}

@using (Html.BeginForm())
{
    <div class="container" style="background:#fff;">
        <div class="row">
            @if (TempData["Message"] != null)
            {
                <div class="col-md-12" style="margin-top: 5px;padding: 20px;">
                    <div class="alert alert-success" id="closeMessage">

                        <span>@TempData["Message"]</span>
                    </div>
                </div>
            }
            else
            {
        <div class="col-sm-12 form-group" style="padding: 15px;">
            <div class="col-sm-6 form-group">
                <label>Bank Name</label>
                @Html.TextBoxFor(p => p.BankName, new { @class = "form-control", placeholder = "Enter bank name.." })
            </div>
            <div class="col-sm-6 form-group">
                <label>Branch Name</label>
                @Html.TextBoxFor(p => p.BranchName, new { @class = "form-control", placeholder = "Enter branch name.." })
            </div>
            <div class="col-sm-6 form-group">
                <label>Area</label>
                @Html.TextBoxFor(p => p.Area, new { @class = "form-control", placeholder = "Enter area.." })
            </div>
            <div class="col-sm-6 form-group">
                <label>Account No</label>
                @Html.TextBoxFor(p => p.AccountNumber, new { @class = "form-control", placeholder = "Enter account number.." })
            </div>
            <div class="col-sm-6 form-group">
                <label>IFSC/NEFT Code</label>
                @Html.TextBoxFor(p => p.NEFTCode, new { @class = "form-control", placeholder = "Enter ifsc code.." })
            </div>
            <div class="col-sm-6 form-group">
                <input type="submit" class="btn btn-success pull-left" style="margin-top:27px;" />
            </div>
            <div class="col-sm-12 form-group">
                @Html.HiddenFor(p => p.Counter)
            </div>


        </div>
            }
        </div>
    </div>
}

Agency_Backoffice/Agency_Backoffice/Views/Wallet/ReportUploadRequest.cshtml
@model ModelLibrary.UploadRequest
@{
    ViewBag.Title = "ReportUploadRequest";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@section header
{
    <link href="~/Content/css/DatePickerMYcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
}

<div class="col-md-12 col-sm-12">
    <div class="x_panel">       
        <div class="x_content">
            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading">
                                <i class="icofont-search-document"></i>  Uploaded Report
                                <span class="tools pull-right">
                                    <a href="/backoffice/wallet/uploadrequest" class="btn btn-success" style="cursor: pointer; margin-top: -6px; color: #fff; line-height: 0; border: none;"><span class="icofont-upload-alt"></span> Upload Request</a>
                                </span>
                            </header>
                            <div class="panel-body" style="padding:15px;">
                                @using (Html.BeginForm("ReportUploadRequest", "Wallet"))
                                {
                                    <div class="row form-group">
                                        <div class="col-sm-12 form-group">
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.FilterFromDate, new { @class = "form-control CommanDate", placeholder = "From Date", @readonly = "readonly" })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.FilterToDate, new { @class = "form-control CommanDate", placeholder = "To Date", @readonly = "readonly" })
                                            </div>
                                            <div class="col-sm-3">

                                                @Html.DropDownListFor(model => model.FilterPaymentType, new SelectList(new List<Object>{
                                                         new { value = "" , text = "--Payment Type--" },
                                                        new { value = "Cash" , text = "Cash" },
                                                        new { value = "Cash Deposite In Bank" , text = "Cash Deposite In Bank"},
                                                          new { value = "NetBanking" , text = "NetBanking"},
                                                          new { value = "RTGS" , text = "RTGS"},
                                                     }, "value", "text"), new { @class = "form-control" })
                                            </div>
                                            <div class="col-sm-3">

                                                @Html.DropDownListFor(model => model.FilterStatus, new SelectList(new List<Object>{
                                                         new { value = "" , text = "--Status--" },
                                                        new { value = "Pending" , text = "Pending" },
                                                        new { value = "InProcess" , text = "InProcess"},
                                                          new { value = "Confirm" , text = "Confirm"},
                                                          new { value = "Rejected" , text = "Rejected"},
                                                     }, "value", "text"), new { @class = "form-control" })
                                            </div>
                                            <div class="col-sm-2">
                                                <input type="submit" class="btn btn-success form-control" style="cursor:pointer;margin-top:1px;" id="btnSearch" value="SEARCH" onclick="return FilterSearch();" />
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </section>
                    </div>
                </div>
            </section>
            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading">
                                <i class="icofont-search-document"></i>  Ticket Report
                                @*<span class="tools pull-right">
                                    <button style="cursor:pointer;"><span class="icofont-file-excel"></span> Export</button>
                                </span>*@
                            </header>
                            <div class="panel-body table-responsive" style="overflow:scroll;">
                                <table class="table table-collapse-phone" cellspacing="0" width="100%" ShowHeaderWhenEmpty="true">
                                    <thead>
                                        <tr>
                                            <th>Deposite Date</th>
                                            @*<th>Agency Name	</th>*@
                                            <th>User_Id</th>
                                            <th>Amount</th>
                                            <th>Mode Of Payment</th>
                                            <th>Bank Name</th>
                                            <th>Cheque No</th>
                                            <th>Cheque Date</th>
                                            <th>Transaction Id</th>
                                            <th>Bank Area Code</th>
                                            <th>Deposite City</th>
                                            <th>Deposite Office</th>
                                            <th>Concern Person</th>
                                            <th>Reciept No</th>
                                            <th>Remark</th>
                                            <th>Status</th>
                                            <th>Remark By Account</th>
                                            <th>Account Id</th>
                                            <th>Created Date</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align:center;">
                                        @if (Model.Totalcount > 0)
                                        {
                                            foreach (var item in Model.UploadDetialsList)
                                            {
                                                <tr>
                                                    <td>@item.DepositeDate</td>
                                                    @*<td>@item.AgencyName</td>*@
                                                    <td>@item.AgencyID</td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.ModeOfPayment</td>
                                                    <td>@item.BankName</td>
                                                    <td>@item.ChequeNo</td>
                                                    <td>@item.ChequeDate</td>
                                                    <td>@item.TransactionID</td>
                                                    <td>@item.BankAreaCode</td>
                                                    <td>@item.DepositCity</td>
                                                    <td>@item.DepositeOffice</td>
                                                    <td>@item.ConcernPerson</td>
                                                    <td>@item.RecieptNo</td>
                                                    <td>@item.Remark</td>
                                                    @if (item.Status == "Pending")
                                                    {
                                                        <td><span style="color:orange;">@item.Status</span></td>
                                                    }
                                                    else
                                                    {
                                                        <td>@item.Status</td>
                                                    }
                                                    <td>@item.RemarkByAccounts</td>
                                                    <td>@item.AccountID</td>
                                                    <td>@item.Date</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr class="no-records-found text-danger"><td colspan="19">No matching records found</td></tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@section footer
{
    <script src="~/Content/js/loginpage/DatePicker.js"></script>
    <script src="~/Content/js/custom/uploadrequest.js"></script>
    <script src="~/Content/js/progressbar.js"></script>
}