Agency_Backoffice/Agency_Backoffice/Controllers/FlightReportController.cs
using Agency_Backoffice.Models;
using Agency_Backoffice.Models.Common;
using Agency_Backoffice.Service;
using ClosedXML.Excel;
using DataBaseLibrary.Flight;
using DataBaseLibrary.MailingCredentiaL;
using ModelLibrary;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using UtilityLibrary;

namespace Agency_Backoffice.Controllers
{
    public class FlightReportController : Controller
    {
        public ActionResult TicketReport(FlightTicketFilter filter)
        {
            FlightTicketReport model = new FlightTicketReport();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    filter.UserType = lu.AgentRegisterSession.User_Type;
                    filter.Loginid = lu.AgentRegisterSession.UID;
                    filter.Status = FlightStatus.Ticketed.ToString();                    
                }

                model.FlightTicketReportList = FlightReportService.GetFlightTicketReports(filter);
                model.Totalcount = model.FlightTicketReportList.Count;

                TempData["FlightFilter"] = filter;
                TempData.Keep();
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public ActionResult TicketDetailsReport(string orderId, string transId)
        {
            SingleTicketReportModel model = new SingleTicketReportModel();
            try
            {
                model.BookingDetail = FlightReportService.GetBookingDetails(orderId);
                model.PaymentDetail = FlightReportService.GetPayementProcess(orderId);
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public JsonResult GetTicketDetails(string orderid)
        {
            return Json(FlightReportService.GetTicketDetails(orderid), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Invoice(string orderId)
        {
            FlightInvoice model = new FlightInvoice();
            try
            {
                //    model.FlightInvoiceList = FlightReportService.GetInvoiceDetails(orderId);
                //    model.PaxList = FlightReportService.SelectPaxDetail(orderId, "");
                //    model.FltDetailsList = FlightReportService.SelectFlightDetail(orderId);
                //    model.FlightInvoiceList[0].DepartureDate = Commoncls.GetSpilitedDateFormate(model.FlightInvoiceList[0].DepartureDate);
                //    model.AgencyList = FlightReportService.GetAgencyDetailByAgentId(model.FlightInvoiceList[0].AgentId);
                model.OrderId = orderId;
                model.Invoicecopy = FlightDataBase.InvoiceCopy(orderId);

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }
        public ActionResult ReIssueReFund(ReIssueReFund model, string paxid, string paxname, string orderid, string gdspnr, string paxtype, string actiontype)
        {
            try
            {
                if (!string.IsNullOrEmpty(paxid) && !string.IsNullOrEmpty(actiontype))
                {
                    if (actiontype == "reissue")
                    {
                        string firstStatus = FlightReportService.CheckTktNo(Convert.ToInt32(paxid), orderid, gdspnr);

                        model = FlightReportService.GetTicketdIntl(Convert.ToInt32(paxid), paxtype);

                        string newpaxid = paxid;

                        if (!string.IsNullOrEmpty(model.ResuID))
                        {
                            ReIssueReFund Paxds = FlightReportService.OldPaxInfo(model.ResuID, model.Title, model.FName, model.MName, model.LName, model.PaxType);
                            //newpaxid = Paxds.PaxId.ToString();
                        }

                        string secondStatus = FlightReportService.CheckTktNo(Convert.ToInt32(newpaxid.Trim()), model.OrderId, model.PNR);

                        if (secondStatus == "0")
                        {
                        }
                        else if (secondStatus == "Reissue request can not be accepted for past departure date." && actiontype == "refund")
                        {
                        }
                        else if ((secondStatus == "0" || secondStatus == "Reissue request can not be accepted for past departure date." || secondStatus == "Given ticket number is already ReIssued") || firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {

                        }
                        else if (firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {
                        }
                        else
                        {
                            TempData["Message"] = secondStatus;
                        }
                    }
                    else
                    {
                        string firstStatus = FlightReportService.CheckTktNo(Convert.ToInt32(paxid), orderid, gdspnr);

                        model = FlightReportService.GetTicketdIntl(Convert.ToInt32(paxid), paxtype);

                        string newpaxid = paxid;

                        if (!string.IsNullOrEmpty(model.ResuID))
                        {
                            ReIssueReFund Paxds = FlightReportService.OldPaxInfo(model.ResuID, model.Title, model.FName, model.MName, model.LName, model.PaxType);
                            //newpaxid = Paxds.PaxId.ToString();
                        }

                        string secondStatus = FlightReportService.CheckTktNo(Convert.ToInt32(newpaxid.Trim()), model.OrderId, model.PNR);

                        if (secondStatus == "0")
                        {
                        }
                        else if (secondStatus == "Reissue request can not be accepted for past departure date." && actiontype == "refund")
                        {
                        }
                        else if ((secondStatus == "0" || secondStatus == "Reissue request can not be accepted for past departure date." || secondStatus == "Given ticket number is already ReIssued") || firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {

                        }
                        else if (firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {
                        }
                        else
                        {
                            TempData["Message"] = secondStatus;
                        }
                    }

                    model.ActionType = actiontype.ToUpper();
                }

                model.PaxName = paxname;
            }
            catch (Exception ex)
            {
                ex.ToString();
                //clsErrorLog.LogInfo(ex)
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult ReIssueReFund(ReIssueReFund model, string actiontype)
        {
            try
            {
                if (model.ActionType.ToLower() == "refund")
                {

                }
                else
                {
                    if (model.ActionType.ToLower() == "reissue")
                    {
                        ReIssueReFund fltds = FlightReportService.GetTicketdIntl(Convert.ToInt32(model.PaxID), model.PaxType);
                        if (fltds != null && !string.IsNullOrEmpty(fltds.UserID))
                        {
                            string status = FlightReportService.CheckTktNo(Convert.ToInt32(model.PaxID), model.OrderId, model.PNR);

                            if (status == "0")
                            {
                                fltds.Remark = model.Remark;
                                fltds.PaxID = model.PaxID;
                                fltds.ProjectID = !string.IsNullOrEmpty(model.ProjectID) ? model.ProjectID : "Nothing";
                                fltds.BillNoAir = !string.IsNullOrEmpty(model.BillNoAir) ? model.BillNoAir : "Nothing";
                                fltds.BillNoCorp = "Nothing";
                                fltds.ReqTyp = "R";
                                fltds.Status = FlightStatus.Pending.ToString();
                                fltds.RefundID = UtilityModel.GenrateRandomTransactionId("RISU", 10, "1234567890");

                                if (model.ActionType.ToLower() == "reissue")
                                {
                                    bool isInsert = FlightReportService.InsertReIssueCancelIntl(fltds);

                                    LoginSessionDetails lu = new LoginSessionDetails();
                                    if (AccountService.GetLoginSession(ref lu))
                                    {
                                        if (!string.IsNullOrEmpty(lu.AgentRegisterSession.LoginByOTP) && lu.AgentRegisterSession.LoginByOTP.ToLower().Trim() == "true")
                                        {
                                            string UserId = lu.AgentRegisterSession.UID;
                                            string Remark = model.Remark;
                                            string OTPRefNo = fltds.OrderId;

Agency_Backoffice/Agency_Backoffice/Views/FlightReport/HoldPNRReport.cshtml
@model ModelLibrary.FlightTicketReport
@{
    ViewBag.Title = "HoldPNRReport";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
<link href="~/Content/css/DatePickerMYcss.css" rel="stylesheet" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="col-md-12">
    <div class="x_panel">
        @*<div class="x_title">
            <div class="row">
                <div class="col-sm-10">
                    <h4><i class="fa fa-list"></i>&nbsp;Hold Pnr Report</h4>
                </div>
              

            </div>
            <div class="clearfix"></div>
        </div>*@
     
            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Hold PNR Report

                            </header>
                            <div class="panel-body" style="padding:15px;">
                                @using (Html.BeginForm())
                                {
                                    <div class="row form-group">
                                        <div class="col-sm-12">
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.FromDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy" })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.ToDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy" })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.PNR, new { @class = "form-control", placeholder = "PNR.." })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.OrderId, new { @class = "form-control", placeholder = "Orderid.." })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.PaxName, new { @class = "form-control", placeholder = "Pax name.." })
                                            </div>
                                            <div class="col-sm-2">

                                                @Html.TextBoxFor(p => p.AirlinePNR, new { @class = "form-control", placeholder = "TicketNo.." })
                                            </div>
                                            <div class="col-sm-2">
                                                <input type="submit" class="btn btn-success form-control maincss" style="cursor:pointer;margin-top:1px;" onclick="return CheckForm()" value="SEARCH RESULT" />
                                                <span class="btn btn-success form-control tempscss hidden" style="margin-top: 1px;margin-top:1px;">PLEASE WAIT..<i class="fa fa-spinner fa-spin"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                 
                                }
                            </div>
                        </section>
                    </div>
                </div>
            </section>


            <section class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Ticket Report
                                <span class="tools pull-right">
                                    @if (Model.Totalcount > 0)
                                    {
                                        using (Html.BeginForm("HoldPnrReportExportToExcel", "FlightReport", FormMethod.Post))
                                        {
                                            <button type="submit" style="cursor:pointer;"><span class="icofont-file-excel"></span> Export</button>
                                        }
                                    }
                                </span>
                            </header>
                            <div class="panel-body table-responsive" style="overflow:scroll;">
                                <table class="table table-collapse-phone" cellspacing="0" width="100%" ShowHeaderWhenEmpty="true">
                                    <thead>
                                        <tr>
                                            <th class="sticky-header">Order Id</th>
                                            <th>Pnr</th>
                                            <th>Sector</th>
                                            <th>Status</th>
                                            <th>Duration</th>
                                            <th>Total Amt</th>
                                            <th>Net Amt</th>
                                            <th>Pax Name</th>
                                            <th>Mobile</th>
                                            <th>Email</th>
                                            <th>Date</th>
                                            <th>Payment Mode</th>
                                            <th>Pg Charges</th>
                                            <th>Hold Charges</th>
                                            <th>Hold Booking</th>
                                            <th>Issue_Hold_Ticket</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.Totalcount > 0)
                                        {
                                            foreach (var item in Model.FlightTicketReportList)
                                            {
                                                <tr>
                                                    <td class="sticky-row"><a href="#">@item.OrderId</a></td>
                                                    <td>@item.GdsPnr</td>
                                                    <td>@item.Sector</td>
                                                    <td>@item.Status</td>
                                                    <td>@item.Duration</td>
                                                    <td>@item.TotalBookingCost</td>
                                                    <td>@item.TotalBookingCost</td>
                                                    <td>@item.PgTitle @item.PgFName @item.PgLName</td>
                                                    <td>@item.PgMobile</td>
                                                    <td>@item.PgEmail</td>
                                                    <td>@item.CreateDate</td>
                                                    <td>@item.PaymentMode</td>
                                                    <td>@item.PGCharges</td>
                                                    <td>@item.HoldCharge</td>
                                                    <td>@item.IsHoldByAgent </td>
                                                    <td>@item.HoldDateTime</td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                            </section>
                        </div>
                    </div>
                </section>
                   
                </div>
        </div>

<script src="~/Content/js/loginpage/DatePicker.js"></script>
<script>
    function CheckForm() {
        $('.maincss').addClass('hidden');
        $('.tempscss').removeClass('hidden');
    }
</script>

Agency_Backoffice/Agency_Backoffice/Views/FlightReport/ReIssueReFund.cshtml
@model ModelLibrary.ReIssueReFund

@{
    ViewBag.Title = "ReIssueReFund";
    Layout = "~/Views/Shared/_PopupLayoutPage.cshtml";
}

@section header
{
    <link href="~/Content/css/validation.css" rel="stylesheet" />
}

<div class="x_panel">
    <div class="x_title">
        <h2><i class="fa fa-bars"></i> @Model.ActionType</h2>
        <div class="clearfix"></div>
    </div>
    @if (TempData["Message"] != null)
    {
        <div class="x_content">
            <div class="row form-group">
                <div class="col-md-12 col-sm-12  form-group">
                    <h4 class="text-center">@TempData["Message"]</h4>
                </div>
            </div>
        </div>
    }
    else
    {
        using (Html.BeginForm())
        {
            @Html.HiddenFor(p => p.PaxID)
            @Html.HiddenFor(p => p.Sector)
            @Html.HiddenFor(p => p.OrderId)
            @Html.HiddenFor(p => p.PNR)
            @Html.HiddenFor(p => p.PaxType)
            @Html.HiddenFor(p => p.ActionType)

            <div class="x_content">
                <div class="row form-group ">
                    <div class="col-md-4 col-sm-12  form-group">
                        <label>PNR: <span style="font-weight:100;">@Model.PNR</span></label>
                    </div>
                    <div class="col-md-4 col-sm-12  form-group">
                        <label>Ticket No: <span style="font-weight:100;">@Model.TicketNo</span></label>
                    </div>
                    <div class="col-md-4 col-sm-12  form-group">
                        <label>Pax Name: <span style="font-weight:100;">@Model.PaxName</span></label>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2 col-sm-12  form-group">
                        <h4> Remark:</h4>
                    </div>
                    <div class="col-md-10 col-sm-12  form-group form-validation">
                        @Html.TextAreaFor(p => p.Remark, new { @class = "form-control", placeholder = "Remark..." })
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right" id="btnSubmit" onclick="return CheckForm();">Submit</button>
                    </div>
                </div>
            </div>
        }
    }
</div>

@section footer
{
    <script>
        function CheckForm() {            
            if (CheckBlankValidation("Remark")) return !1;
            $("#btnSubmit").html("Please Wait... <i class='fa fa-pulse fa-spinner'></i>");
        }
    </script>
}

Agency_Backoffice/Agency_Backoffice/Views/FlightReport/RefundReport.cshtml
@model ModelLibrary.FlightTicketReport
@{
    ViewBag.Title = "RefundReport";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
<link href="~/Content/css/DatePickerMYcss.css" rel="stylesheet" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="col-md-12">
    <div class="x_panel">
        @*<div class="x_title">
                <div class="row ">
                    <div class="col-sm-10 ">
                        <h4><i class="fa fa-list"></i>&nbsp;Refund Report List</h4>
                    </div>


                </div>
                <div class="clearfix"></div>
            </div>*@
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Refund Report

                        </header>
                        <div class="panel-body" style="padding:15px;">
                            @using (Html.BeginForm())
                            {
                                <div class="row form-group">

                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.FromDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy" })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.ToDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy" })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.PNR, new { @class = "form-control", placeholder = "PNR.." })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.OrderId, new { @class = "form-control", placeholder = "Orderid.." })
                                    </div>

                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.PaxName, new { @class = "form-control", placeholder = "Pax name.." })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.TicketNo, new { @class = "form-control", placeholder = "TicketNo.." })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.TextBoxFor(p => p.AirlinePNR, new { @class = "form-control", placeholder = "TicketNo.." })
                                    </div>
                                    <div class="col-sm-2">

                                        @Html.DropDownListFor(model => model.Trip, new SelectList(new List<Object>{
                                                 new { value = "" , text = "--Trip Type--" },
                                                new { value = "D" , text = "Domestic" },
                                                new { value = "I" , text = "International"},
                                             }, "value", "text"), new { @class = "form-control" })
                                    </div>

                                    <div class="col-sm-2">
                                        <input type="submit" class="btn btn-success form-control maincss" style="cursor:pointer;" onclick="return CheckForm()" value="SEARCH RESULT" />
                                        <span class="btn btn-success form-control tempscss hidden">PLEASE WAIT..<i class="fa fa-spinner fa-spin"></i></span>
                                    </div>
                                </div>


                            }
                        </div>
                    </section>
                </div>
            </div>
        </section>

        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            <i class="icofont-search-document"></i>  Ticket Report
                            <span class="tools pull-right">
                                @if (Model.Totalcount > 0)
                                {
                                    using (Html.BeginForm("RefundReportExportToExcel", "FlightReport", FormMethod.Post))
                                    {
                                        <button type="submit" style="cursor:pointer;"><span class="icofont-file-excel"></span> Export</button>
                                    }
                                }
                            </span>
                        </header>
                        <div class="panel-body table-responsive" style="overflow:scroll;">
                            <table class="table table-collapse-phone" cellspacing="0" width="100%" ShowHeaderWhenEmpty="true">
                                <thead>
                                    <tr>
                                        <th class="sticky-header">Credit Node</th>
                                        @*<th>Customer Id</th>
                                            <th>Agency Name</th>*@
                                        <th>P Type</th>
                                        <th>P Name</th>
                                        <th>Pnr</th>
                                        <th>Ticket Number#</th>
                                        <th>Carrier</th>
                                        <th>Sector	</th>
                                        <th>Date</th>
                                        <th>T Fare</th>
                                        <th>Fare After Discount</th>
                                        <th>Cancellation Charge</th>
                                        <th>Sevice Charge</th>
                                        <th>Refunded Fare</th>
                                        <th>Comment</th>
                                        <th>Exec Id</th>
                                        <th>Exec Rejected Remark</th>
                                        <th>Exec Updated Remark</th>
                                        <th>Refund Status</th>
                                        <th>Requested Date</th>
                                        <th>Accepted Date</th>
                                        <th>Updated Date</th>
                                        <th>Cancle Status</th>
                                        <th>Payment Mode</th>
                                        <th>Pg Charges</th>
                                    </tr>
                                </thead>
                                <tbody style="text-align:center;">
                                    @if (Model.Totalcount > 0)
                                    {
                                        foreach (var item in Model.FlightTicketReportList)
                                        {
                                            <tr>
                                                <td class="sticky-row"><a href="#">@item.RefundID</a></td>
                                                @*<td>@item.StaffId</td>
                                                    <td>@item.AgencyName</td>*@
                                                <td>@item.PaxType</td>
                                                <td>@item.PgTitle @item.PgFName @item.PgLName</td>
                                                <td>@item.Pnr_Locator</td>
                                                <td>@item.TicketNo</td>
                                                <td>@item.VC</td>
                                                <td>@item.Sector</td>
                                                <td>@item.JourneyDate</td>
                                                <td>@item.TotalBookingCost</td>
                                                <td>@item.TotalAfterDis</td>
                                                <td>@item.CancellationCharge</td>
                                                <td>@item.Service_Tax</td>
                                                <td>@item.ResuFareDiff</td>
                                                <td>@item.RegardingCancel</td>
                                                <td>@item.ExecutiveId</td>
                                                <td>@item.RejectedRemark</td>
                                                <td>@item.Remark</td>
                                                <td>@item.Status</td>
                                                <td>@item.SubmitDate</td>
                                                <td>@item.AcceptDate</td>
                                                <td>@item.UpdateDate</td>
                                                <td>@item.CancelStatus</td>
                                                <td>@item.PaymentMode</td>
                                                <td>@item.PGCharges</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </div>
</div>

<script src="~/Content/js/loginpage/DatePicker.js"></script>
<script>
    function CheckForm() {
        $('.maincss').addClass('hidden');
        $('.tempscss').removeClass('hidden');
    }
</script>